image: python:3.7-alpine

pages:
  stage: deploy
  script:
  - pip install -U sphinx
  - pip install myst-parser
  - pip install sphinx-autoapi
  - sphinx-build -b html docs/ public
  artifacts:
    paths:
    - public
  only:
  - master
