image: python:3.7-alpine

pages:
  stage: deploy
  script:
  - pip install sphinx
  - pip install sphinx-autoapi
  - pip install myst-parser
  - cd docs 
  - sphinx-build -b html . public
  artifacts:
    paths:
    - public
  only:
  - master
